### ISSUE TITLE
Retain page when switching version

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/addons#223] opened 2023-12-19 14:02 UTC
Without add-ons, when the reader switches the version in the flyout, they land in the same page. For example:

1. Open https://docs.poliastro.space/en/stable/quickstart.html
2. Click "0.17.x" in the flyout
3. Land in https://docs.poliastro.space/en/0.17.x/quickstart.html ✔️ 

Now, with add-ons, when the reader switches the version in the flyout, they land in the home page. For example:

1. Open https://docs.kedro.org/en/stable/introduction/index.html
2. Click "0.19.0" in the flyout
3. Land in https://docs.kedro.org/en/0.19.0/ ❌ 

The current behavior prevents arriving to a 404 page in cases where the current page doesn't exist in the other version (https://github.com/readthedocs/readthedocs.org/issues/10643) but makes it more difficult to see differences between versions, and requires extra clicks to arrive where you were.

Is this intentional?

**Comment by humitos** [comment] 2023-12-19 14:59
> Is this intentional?

It is intentional... _for now_, at least 😄 

The same issue was reported at #211 (please, subscribe there) and I have some doubts about how to implement this in a way that gives a good UX to users. I need to think more about _how to do it properly_.

I'm closing this issue as duplicate of #211.

**Closed by humitos** 2023-12-19 14:59 UTC
