### ISSUE TITLE
Normal search stops working for old versions when add-ons are enabled

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/addons#219] opened 2023-12-14 11:10 UTC
See for example: https://docs.kedro.org/en/0.17.1/search.html?q=partitioned&check_keywords=yes&area=default

![image](https://github.com/readthedocs/addons/assets/316517/b4138369-fe14-4b49-bfbc-25fef9f49c50)

The search from the flyout displays the search-as-you-type modal and everything works. But the Sphinx search box (which doesn't trigger the relevant event, because it hasn't been modified) takes the user to an empty page.

cc @inigohidalgo @rashidakanchwala

**Comment by humitos** [comment] 2023-12-14 12:20
Hi @astrojuanlu! Can you try rebuilding the old version please and letting me know if it solves the issue?

(I'm from the phone 📱)

**Comment by astrojuanlu** [comment] 2023-12-14 13:47
I tried rebuilding but it failed https://beta.readthedocs.org/projects/kedro/builds/22854520/ because of https://blog.readthedocs.com/use-build-os-config/

We don't follow the ["versions as branches" approach](https://github.com/readthedocs/blog/pull/74/) so I don't think we'll rebuild very old versions of the docs. But if it helps troubleshooting, I can try to do an experiment with some other project (I'd need some time to think which).

**Comment by humitos** [comment] 2023-12-14 16:59
Hrm... This is an interesting scenario 🤔 . The fix deployed in #213 works only when rebuilding the documentation, so it won't have any effect on those old versions that can't be re-built 😢 . At least, it stop the issue to keep propagating on new projects, tho.

I will need to think more about this case because I don't have a clear solution in mind about how we can fix this in older versions that are static and don't allow rebuilding. However, I'm not sure if there is a _generic_ solution that works for all the cases... 😞  I need to think more 🧠

**Comment by humitos** [comment] 2023-12-17 11:40
I found a way to fix this and I opened a PR internally. Hopefully it can be reviewed in the following days and deployed. I will let you know when it's deployed so you can confirm the issue is solved 👍🏼

**Comment by humitos** [comment] 2023-12-18 10:59
I deployed a fix for this. @astrojuanlu can you please confirm that's working as you expected?

Note that this starts working on version 0.18.4, because it seems the older versions were built with older Sphinx versions where the search was broken on their side it seems --I didn't find anything related to Read the Docs at least [^1]:

* https://github.com/sphinx-doc/sphinx/issues/9714
* https://github.com/sphinx-doc/sphinx/issues/8623
* https://github.com/sphinx-doc/sphinx/issues/8591


On 0.18.4 works fine for me: https://docs.kedro.org/en/0.18.4/search.html?q=partitioned&check_keywords=yes&area=default

[^1]: if you notice an issue in our side I'm happy to trace it down a little more and try to find a solution.

**Closed** 2023-12-18 17:44 UTC

**Comment by astrojuanlu** [comment] 2023-12-19 08:43
This is great, thanks @humitos! Yeah nothing can be done with old Sphinx versions 😅 but at least we're in a better place now
