### ISSUE TITLE
`Esc` doesn't close the search-as-you-type modal

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/addons#216] opened 2023-12-12 10:10 UTC
Been trying on https://astrojuanlu-kedro-test.readthedocs.io/en/latest/ to no avail. Nothing happens and I don't see any errors in the console.

![image](https://github.com/readthedocs/addons/assets/316517/7b24f1f1-0ac7-40c8-83c7-0ce7ba77e893)

**Comment by humitos** [comment] 2023-12-12 10:55
Yeah, this is not working. We have an issue opened for this at #172. Closing as duplicate of that one. Please, subscribe there 👍🏼

**Closed by humitos** 2023-12-12 10:55 UTC
