### ISSUE TITLE
Notification: allow to disable `latest` and/or non-`stable` warning

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#133] opened 2023-09-18 11:31 UTC
The current pretty simple logic we have is good and it may work for most of the cases. However, it's a little verbose since _it will show a notification in all the versions that are not `stable`_ --which could be _a lot_.

There are users that won't like this pattern and may not want to follow "our proposal to use the platform" here (most users should always read the `stable` version of the project's documentation) or may require an un-supported way to decide "stable" version.

These users should be able to decide whether or not show a warning notification on `latest` and/or on non-`stable` versions independently:

* Enable the addons (disable it completely)
* Show a notification on non-`stable` versions
* Show a notification on `latest` version

Related

* #125
* https://github.com/readthedocs/ext-theme/issues/212
* https://github.com/readthedocs/ext-theme/issues/211
* https://github.com/cilium/cilium/issues/29969
* https://github.com/readthedocs/addons/issues/201

**Comment by Zylann** [comment] 2024-05-02 18:11
Is it about this warning?
![image](https://github.com/readthedocs/addons/assets/1311555/48f221fb-5c60-4e16-9957-b70c4010affb)

I started noticing it only a few weeks ago, and I don't know how to get rid of it, since most users of my project use its latest version.

**Comment by humitos** [comment] 2024-05-06 15:38
Hi @Zylann. This is new to Read the Docs as well. We have been migrating a lot of features we used to perform in the backend build process to a front-end application.

You can read more about this in our blog:
* https://blog.readthedocs.com/addons-flyout-menu-beta/
* https://about.readthedocs.com/blog/2024/04/enable-beta-addons/

Note that you can disable this notification from your project's setting using the beta dashboard (more info about this in the second blog post). Let me know if that helps.

**Comment by agilgur5** [comment] 2024-06-23 16:29
> Also even if it were desired, it covers the top of every page, requiring action to dismiss it each time.

Yes, this is pretty annoying, especially for contributors who use `latest` regularly (see also [this thread](https://cloud-native.slack.com/archives/C0510EUH90V/p1717527464903189?thread_ts=1717527464.903189&cid=C0510EUH90V) in CNCF Slack for Argo Workflows contributors).

If it were less obtrusive or had a cookie or checkbox to remember that I hid it, that would be much nicer. For instance:
- default to hide it for a week
- allow users to optionally hide it -- some are well aware they are on a different version than stable
- make it smaller at the top of the page, like a banner. as an example, here is [`mkdocs-material`'s version warning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning) that is just above the header and so can just be scrolled past.

Otherwise, given how obtrusive it currently is, we will probably disable it entirely. I found this issue searching for how to disable it.

**Comment by humitos** [comment] 2024-06-23 16:34
Thanks for your feedback @agilgur5 👍

> If it were less obtrusive or had a cookie or checkbox to remember that I hid it, that would be much nicer

This is already implemented and will be deployed next week.

**Comment by humitos** [comment] 2024-06-25 08:48
I just deployed a new version of the addons that includes the ability to dismiss a notification and not show it again on the same project/language/version. Feel free to open a new issue with any feedback you may have. Thanks 🙏🏼 cc @agilgur5

**Comment by agilgur5** [comment] 2024-06-26 23:14
> includes the ability to dismiss a notification and not show it again on the same project/language/version

Looks like it happens automatically? I didn't see an _option_, but I do see it remembers the dismissal and stores a timestamp in `localStorage`.

Looks like per #283 it's just permanent for now?
And I see this issue is roughly a duplicate of #46

**Comment by humitos** [comment] 2024-06-27 08:48
@agilgur5 yes, it's permanent for now. We released this simplified version as a first step, but we plan to improve it with the feedback we receive.

**Closed** 2024-11-04 10:15 UTC
Labels: Improvement, Accepted
